import { MAIN_COLOR } from "@/app/constants";
import { StyleSheet } from "react-native";

export const stylesBaseStylesCreateGasto = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAF9",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#E1E8E6",
    shadowColor: MAIN_COLOR,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: MAIN_COLOR,
    flex: 1,
    textAlign: "center",
  },
  placeholder: {
    width: 40,
  },
  content: {
    flex: 1,
  },
  form: {
    padding: 20,
  },
  sectionHeader: {
    marginTop: 10,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: MAIN_COLOR,
  },
  inputGroup: {
    marginBottom: 10,
  },
  label: {
    fontSize: 16,
    fontWeight: "600",
    color: MAIN_COLOR,
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: "#E1E8E6",
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    backgroundColor: "#fff",
    color: MAIN_COLOR,
    shadowColor: MAIN_COLOR,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: "#E1E8E6",
    borderRadius: 12,
    backgroundColor: "#fff",
    shadowColor: MAIN_COLOR,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  picker: {
    height: 50,
    color: MAIN_COLOR,
  },
  customSelector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#E1E8E6",
    borderRadius: 12,
    padding: 16,
    backgroundColor: "#fff",
    shadowColor: MAIN_COLOR,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
    minHeight: 56,
  },
  selectorText: {
    fontSize: 16,
    color: MAIN_COLOR,
    flex: 1,
  },
  selectorPlaceholder: {
    color: "#8A9A97",
  },
  selectorModalContent: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "70%",
    paddingBottom: 20,
  },
  selectorModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E1E8E6",
  },
  selectorModalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: MAIN_COLOR,
  },
  selectorOptions: {
    maxHeight: 400,
  },
  selectorOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F7F5",
  },
  selectorOptionText: {
    fontSize: 16,
    color: MAIN_COLOR,
    flex: 1,
  },
  selectorOptionSelected: {
    fontWeight: "600",
    color: MAIN_COLOR,
  },
  addFileButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderWidth: 2,
    borderColor: MAIN_COLOR,
    borderStyle: "dashed",
    borderRadius: 12,
    padding: 20,
    marginBottom: 15,
  },
  addFileText: {
    fontSize: 16,
    fontWeight: "600",
    color: MAIN_COLOR,
    marginLeft: 10,
  },
  filesList: {
    maxHeight: 300,
    marginBottom: 20,
  },
  fileItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    marginHorizontal: 4,
    shadowColor: MAIN_COLOR,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#F0F2F5",
  },
  fileImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
  },
  fileIcon: {
    width: 60,
    height: 60,
    borderRadius: 8,
    backgroundColor: "#F0F7F5",
    alignItems: "center",
    justifyContent: "center",
  },
  fileInfo: {
    flex: 1,
    marginLeft: 12,
  },
  fileName: {
    fontSize: 15,
    fontWeight: "600",
    color: MAIN_COLOR,
    marginBottom: 4,
    lineHeight: 20,
  },
  fileSize: {
    fontSize: 13,
    color: "#8A9A97",
    fontWeight: "500",
  },
  removeFileButton: {
    padding: 4,
  },
  submitButton: {
    backgroundColor: MAIN_COLOR,
    borderRadius: 12,
    padding: 18,
    alignItems: "center",
    marginTop: 20,
    shadowColor: MAIN_COLOR,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  submitButtonDisabled: {
    backgroundColor: "#8A9A97",
  },
  buttonText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#fff",
    letterSpacing: 0.5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 40,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: MAIN_COLOR,
    textAlign: "center",
    marginBottom: 20,
  },
  modalOption: {
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    borderRadius: 12,
    marginBottom: 10,
    backgroundColor: "#F8FAF9",
  },
  modalOptionText: {
    fontSize: 16,
    fontWeight: "600",
    color: MAIN_COLOR,
    marginLeft: 15,
  },
  cancelOption: {
    backgroundColor: "#FEF2F2",
    marginTop: 10,
  },
  cancelText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#EF4444",
    textAlign: "center",
    flex: 1,
  },

  // Nuevos estilos para lista de archivos mejorada
  filesContainer: {
    height: 140,
    marginBottom: 20,
    borderRadius: 12,
    backgroundColor: "#F8F9FA",
    padding: 8,
  },
  filesScrollView: {
    paddingVertical: 4,
  },
  filesScrollContent: {
    paddingHorizontal: 8,
    alignItems: "flex-start",
  },

  // Estilos para grid de archivos horizontal
  fileGridItem: {
    width: 100,
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 10,
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#F0F2F5",
    position: "relative",
    height: 120,
  },
  removeFileButtonGrid: {
    position: "absolute",
    top: 6,
    right: 6,
    zIndex: 10,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: 9,
    padding: 1,
  },
  filePreviewGrid: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
  },
  imagePreviewGrid: {
    position: "relative",
    width: "100%",
    height: "100%", // Ocupar todo el card
    borderRadius: 8,
    overflow: "hidden",
  },
  gridImagePreview: {
    width: "100%",
    height: "100%",
    borderRadius: 8,
  },

  fileIconGrid: {
    width: "100%",
    height: 70,
    borderRadius: 8,
    backgroundColor: "#F0F7F5",
    alignItems: "center",
    justifyContent: "center",
  },
  fileInfoGrid: {
    alignItems: "center",
    marginTop: 4,
  },
  fileNameGrid: {
    fontSize: 10,
    fontWeight: "600",
    color: MAIN_COLOR,
    textAlign: "center",
    marginBottom: 2,
    lineHeight: 12,
  },
  fileSizeGrid: {
    fontSize: 9,
    color: "white", // Cambiar a blanco para contraste con fondo oscuro
    fontWeight: "600",
    textAlign: "center",
  },
  filePreviewContainer: {
    marginRight: 12,
  },
  imagePreviewContainer: {
    position: "relative",
    width: 60,
    height: 60,
    borderRadius: 8,
    overflow: "hidden",
  },
  imageOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    borderRadius: 12,
    padding: 4,
    margin: 4,
  },
  fileTypeIndicator: {
    fontSize: 11,
    color: "#6B7280",
    fontStyle: "italic",
    marginTop: 2,
  },

  // Estilos para modal de imagen
  imageModalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.95)",
  },
  imageModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end", // Alinear a la derecha
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
  },
  closeModalButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  imageModalTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "white",
  },
  modalHeaderSpacer: {
    width: 44,
  },
  imageZoomContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  imageZoomScrollView: {
    flex: 1,
    width: "100%",
  },
  fullScreenImage: {
    width: "100%",
    height: "100%",
    maxWidth: 400,
    maxHeight: 600,
  },
  imageModalFooter: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    alignItems: "center",
  },
  zoomInstructions: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.7)",
    textAlign: "center",
  },
});
