import { MAIN_COLOR } from "@/app/constants";
import { StyleSheet } from "react-native";

export const stylesCustomSelectorCreateGasto = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAF9",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#E1E8E6",
    shadowColor: MAIN_COLOR,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: MAIN_COLOR,
    flex: 1,
    textAlign: "center",
  },
  placeholder: {
    width: 40,
  },
  content: {
    flex: 1,
  },
  form: {
    padding: 20,
  },
  sectionHeader: {
    marginTop: 20,
    marginBottom: 15,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#E1E8E6",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: MAIN_COLOR,
  },
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 16,
    fontWeight: "600",
    color: MAIN_COLOR,
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: "#E1E8E6",
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    backgroundColor: "#fff",
    color: MAIN_COLOR,
    shadowColor: MAIN_COLOR,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: "#E1E8E6",
    borderRadius: 12,
    backgroundColor: "#fff",
    shadowColor: MAIN_COLOR,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  picker: {
    height: 50,
    color: MAIN_COLOR,
  },
  customSelector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#E1E8E6",
    borderRadius: 12,
    padding: 16,
    backgroundColor: "#fff",
    shadowColor: MAIN_COLOR,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
    minHeight: 56,
  },
  selectorText: {
    fontSize: 16,
    color: MAIN_COLOR,
    flex: 1,
  },
  selectorPlaceholder: {
    color: "#8A9A97",
  },
  selectorModalContent: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "70%",
    paddingBottom: 20,
  },
  selectorModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E1E8E6",
  },
  selectorModalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: MAIN_COLOR,
  },
  selectorOptions: {
    maxHeight: 400,
  },
  selectorOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F7F5",
  },
  selectorOptionText: {
    fontSize: 16,
    color: MAIN_COLOR,
    flex: 1,
  },
  selectorOptionSelected: {
    fontWeight: "600",
    color: MAIN_COLOR,
  },
  addFileButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderWidth: 2,
    borderColor: MAIN_COLOR,
    borderStyle: "dashed",
    borderRadius: 12,
    padding: 20,
    marginBottom: 15,
  },
  addFileText: {
    fontSize: 16,
    fontWeight: "600",
    color: MAIN_COLOR,
    marginLeft: 10,
  },
  filesList: {
    maxHeight: 300,
    marginBottom: 20,
  },
  fileItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    shadowColor: MAIN_COLOR,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  fileImage: {
    width: 50,
    height: 50,
    borderRadius: 8,
    marginRight: 12,
  },
  fileIcon: {
    width: 50,
    height: 50,
    borderRadius: 8,
    backgroundColor: "#F0F7F5",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  fileInfo: {
    flex: 1,
  },
  fileName: {
    fontSize: 14,
    fontWeight: "600",
    color: MAIN_COLOR,
    marginBottom: 2,
  },
  fileSize: {
    fontSize: 12,
    color: "#8A9A97",
  },
  removeFileButton: {
    padding: 4,
  },
  submitButton: {
    backgroundColor: MAIN_COLOR,
    borderRadius: 12,
    padding: 18,
    alignItems: "center",
    marginTop: 20,
    shadowColor: MAIN_COLOR,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  submitButtonDisabled: {
    backgroundColor: "#8A9A97",
  },
  buttonText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#fff",
    letterSpacing: 0.5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 40,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: MAIN_COLOR,
    textAlign: "center",
    marginBottom: 20,
  },
  modalOption: {
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    borderRadius: 12,
    marginBottom: 10,
    backgroundColor: "#F8FAF9",
  },
  modalOptionText: {
    fontSize: 16,
    fontWeight: "600",
    color: MAIN_COLOR,
    marginLeft: 15,
  },
  cancelOption: {
    backgroundColor: "#FEF2F2",
    marginTop: 10,
  },
  cancelText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#EF4444",
    textAlign: "center",
    flex: 1,
  },
});
